# Generated by Django 3.1.4 on 2020-12-20 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_name', models.CharField(max_length=500)),
                ('album_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(default=None, max_length=500)),
                ('apple_id', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_name', models.CharField(max_length=500)),
                ('artist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(default=None, max_length=500)),
                ('apple_id', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_name', models.CharField(max_length=500)),
                ('track_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(default=None, max_length=500)),
                ('apple_id', models.CharField(default=None, max_length=500)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('description', models.CharField(max_length=500)),
                ('follower', models.ManyToManyField(related_name='who_user_is_followed_by', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='who_user_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_name', models.CharField(max_length=500)),
                ('playlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracks', models.ManyToManyField(to='myapp.Track')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ManyToManyField(to='myapp.Artist'),
        ),
    ]
