# Generated by Django 2.1.12 on 2020-04-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_track_stream_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='preview_url',
            new_name='our_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='track',
            name='apple_url',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_url',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
