# Generated by Django 2.1.12 on 2020-04-22 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200422_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='id',
        ),
        migrations.AlterField(
            model_name='track',
            name='our_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
